# Generated by Django 5.0.6 on 2024-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
