# Generated by Django 5.0.6 on 2024-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_grade_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgrade',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж'), ('З', 'З'), ('И', 'И'), ('Й', 'Й'), ('К', 'К'), ('Л', 'Л'), ('М', 'М'), ('Н', 'Н'), ('О', 'О'), ('П', 'П'), ('Р', 'Р'), ('С', 'С'), ('Т', 'Т'), ('У', 'У'), ('Ф', 'Ф'), ('Х', 'Х'), ('Ц', 'Ц'), ('Ч', 'Ч'), ('Ш', 'Ш'), ('Щ', 'Щ'), ('Ъ', 'Ъ'), ('Ы', 'Ы'), ('Ь', 'Ь'), ('Э', 'Э'), ('Ю', 'Ю'), ('Я', 'Я')], max_length=1),
        ),
    ]
