# Generated by Django 5.0.6 on 2024-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_subgrade_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgrade',
            name='letter',
            field=models.CharField(max_length=1),
        ),
    ]
