# Generated by Django 5.0.6 on 2024-12-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_subgrade_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
