# Generated by Django 5.0.6 on 2024-12-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_grade_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
