# Generated by Django 5.0.6 on 2025-01-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_powerpointupload_remove_grade_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slides/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='PowerPointUpload',
        ),
    ]
