# Generated by Django 5.0.6 on 2025-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_slideshow_delete_powerpointupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPointSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slide', models.ImageField(upload_to='slides/')),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SlideShow',
        ),
    ]
