# Generated by Django 5.0.6 on 2025-01-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_powerpointslide_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerpointslide',
            name='user',
        ),
    ]
