# Generated by Django 5.0.6 on 2025-01-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_powerpointslide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpointslide',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
