# Generated by Django 4.2.18 on 2025-01-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название презентации')),
                ('pdf_file', models.FileField(upload_to='slides/', verbose_name='PDF файл')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='school.school')),
            ],
        ),
        migrations.DeleteModel(
            name='PowerPointSlide',
        ),
    ]
